name: Actions Workflow

on: [ push ]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: list files
        run: |
            pwd
            ls

      - name: Set up working directory
        uses: actions/checkout@v2

      - name: list files
        run: |
            pwd
            ls