name: Actions Workflow

on: [ push ]

jobs:
  actions:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, ubuntu-20.04 ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: list files
        run: |
          pwd
          ls -a
      - name: Set up working directory
        uses: actions/checkout@v3
      - name: list files
        run: |
          pwd
          ls
  actions2:
    needs: actions
    runs-on: ubuntu-20.04
    steps:
      - name: Kick another repo workflow
        uses: convictional/trigger-workflow-and-wait@v1.3.0
        with:
           owner: s3rgh
           repo: github-actions-client
           github_token: ${{ secrets.G_ACCESS_TOKEN }}
           workflow_file_name: from_remote_repo.yml