name: Actions Workflow

on:
  push:
    branches:
    - main

jobs:
  actions:
    runs-on: ubuntu-latest
    steps:
      - name: Tests
        uses: s3rgh/github-actions-client/.github/workflows/remote.yml@main