name: Actions Workflow

on: [ push ]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: list files
        run: |
            pwd
            ls -a

      - name: Set up working directory
        uses: actions/checkout@v3

      - name: list files
        run: |
            pwd
            ls